### ISSUE TITLE
Has issues with Umlauts in Folder names

### ISSUE THREAD

**Issue by cmyk** [nextgis/osmpoly_export#5]
Saving a poly into a folder calle Österreich results in failure.
Also, there's no way to name the file. Sometimes the format dialog appears, sometimes not, seems to depend on the shape layer. Mostly just fails completely.

**Comment by simgislab** [comment]
this is fixed now

regarding naming the output - this is by default, plugin takes the name for the file from the attributes field, it should let you select from which one. If there is just one - it will silently take it.

I'm open for suggestions, feel free to file a feature request. I guess it make sense to allow to choose name in some cases. I'm closing this ticket for now as it saves to Österreich without any problem now.
