### ISSUE TITLE
Error on empty layer

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/osmpoly_export#9]
Traceback (most recent call last):
  File "/home/yellow/.qgis2/python/plugins/osmpoly_export/polygenerator.py", line 129, in run
    infoString = self.tr('No features selected, using all %s features')% str(curLayer.featureCount())
TypeError: not all arguments converted during string formatting

**Comment by simgislab** [comment]
fixed

**Comment by yellow-sky** [comment]
<message>
        <location filename="polygenerator.py" line="129"/>
        <source>No features selected, using all %s features</source>
        <translation>Объекты не выбраны, будут сконвертированы все имеющиеся</translation>
    </message>

**Comment by simgislab** [comment]
I said fixed!)
